version: '3.8'
services:
  jenkins-master:
    build:
        context: .
        dockerfile: Dockerfile
        args:
            UGID: ${UGID}
            UUID: ${UUID}
            DGID: ${DGID}
            SCRIPT_DIR: ${SCRIPT_DIR}
    env_file:
      - ${SCRIPT_DIR}/jcasc/jenkins.env
    ports:
      - 50000:50000
    networks:
      - jenkins
    volumes:
      - ${SCRIPT_DIR}/jenkins_data:/var/jenkins_home
      # - ${SCRIPT_DIR}/logs/jenkins:/var/log/jenkins
      - ${SCRIPT_DIR}/jcasc/jcasc.yml:/var/jenkins_casc.yml
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: cicd-jenkins

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    container_name: cicd-nginx
    restart: unless-stopped
    networks:
      - jenkins
    ports:
      - "8080:80"    # http
      - "8443:443"   # https
    volumes:
      - ${SCRIPT_DIR}/jenkins_data:/var/jenkins_home
      - ${SCRIPT_DIR}/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ${SCRIPT_DIR}/nginx/ssl:/etc/ssl
  
  # agent:
  #   image: jenkins-agent-python
  #   build:
  #       context: .
  #       dockerfile: Dockerfile.agent-jnlp-python

networks:
  jenkins:
    name: cicd-jenkins
    driver: bridge
